version: '3'

services:
  leagueapi:
    image: chalkan33/leagueoflegendsapi
    ports: 
      - 9000:9000
    networks:
      - leagueapi-network

networks:
  leagueapi-network:
    driver: bridge 

